
=====
===== LOGGING STARTED Thu Oct 15 20:24:12 JST 2015
=====
Exec: /home/b-itoh/rc/rel/rc/erts-5.10.4/bin/erlexec -boot /home/b-itoh/rc/rel/rc/releases/1/rc -embedded -config /home/b-itoh/rc/rel/rc/etc/app.config -args_file /home/b-itoh/rc/rel/rc/etc/vm.args -- console
Root: /home/b-itoh/rc/rel/rc
Erlang R16B03-1 (erts-5.10.4) [source] [64-bit] [async-threads:5] [kernel-poll:true]

20:24:13.626 [info] Application lager started on node 'rc@127.0.0.1'
20:24:13.628 [info] Application crypto started on node 'rc@127.0.0.1'
20:24:13.638 [info] Application riak_sysmon started on node 'rc@127.0.0.1'
20:24:13.664 [info] Application os_mon started on node 'rc@127.0.0.1'
20:24:13.667 [info] Application basho_stats started on node 'rc@127.0.0.1'
20:24:13.668 [info] Application eleveldb started on node 'rc@127.0.0.1'
20:24:13.668 [info] Application pbkdf2 started on node 'rc@127.0.0.1'
20:24:13.669 [info] Application poolboy started on node 'rc@127.0.0.1'
20:24:13.724 [info] Starting reporters with []
20:24:13.725 [info] Application exometer_core started on node 'rc@127.0.0.1'
20:24:13.752 [info] Application clique started on node 'rc@127.0.0.1'
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
20:24:13.845 [error] CRASH REPORT Process riak_core_handoff_listener with 1 neighbours exited with reason: bad return value: {error,eaddrinuse} in gen_server:init_it/6 line 332
20:24:13.848 [error] Supervisor riak_core_handoff_listener_sup had child riak_core_handoff_listener started with riak_core_handoff_listener:start_link() at undefined exit with reason bad return value: {error,eaddrinuse} in context start_error
20:24:13.849 [error] Supervisor riak_core_handoff_sup had child riak_core_handoff_listener_sup started with riak_core_handoff_listener_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,riak_core_handoff_listener,{bad_return_value,{error,eaddrinuse}}}} in context start_error
20:24:13.850 [error] Supervisor riak_core_sup had child riak_core_handoff_sup started with riak_core_handoff_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,riak_core_handoff_listener_sup,{shutdown,{failed_to_start_child,riak_core_handoff_listener,{bad_return_value,{error,eaddrinuse}}}}}} in context start_error
20:24:13.852 [error] CRASH REPORT Process <0.119.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,riak_core_handoff_sup,{shutdown,{failed_to_start_child,riak_core_handoff_listener_sup,{shutdown,{failed_to_start_child,riak_core_handoff_listener,{bad_return_value,{error,eaddrinuse}}}}}}}},{riak_core_app,start,[normal,[]]}} in application_master:init/4 line 133
20:24:13.853 [info] Application riak_core exited with reason: {{shutdown,{failed_to_start_child,riak_core_handoff_sup,{shutdown,{failed_to_start_child,riak_core_handoff_listener_sup,{shutdown,{failed_to_start_child,riak_core_handoff_listener,{bad_return_value,{error,eaddrinuse}}}}}}}},{riak_core_app,start,[normal,[]]}} 
{"Kernel pid terminated",application_controller,"{application_start_failure,riak_core,{{shutdown,{failed_to_start_child,riak_core_handoff_sup,{shutdown,{failed_to_start_child,riak_core_handoff_listener_sup,{shutdown,{failed_to_start_child,riak_core_handoff_listener,{bad_return_value,{error,eaddrinuse}}}}}}}},{riak_core_app,start,[normal,[]]}}}"}

Crash dump was written to: erl_crash.dump
Kernel pid terminated (application_controller) ({application_start_failure,riak_core,{{shutdown,{failed_to_start_child,riak_core_handoff_sup,{shutdown,{failed_to_start_child,riak_core_handoff_listen
