2015-10-15 20:24:13.845 [error] <0.131.0> CRASH REPORT Process riak_core_handoff_listener with 1 neighbours exited with reason: bad return value: {error,eaddrinuse} in gen_server:init_it/6 line 332
2015-10-15 20:24:13.848 [error] <0.130.0> Supervisor riak_core_handoff_listener_sup had child riak_core_handoff_listener started with riak_core_handoff_listener:start_link() at undefined exit with reason bad return value: {error,eaddrinuse} in context start_error
2015-10-15 20:24:13.849 [error] <0.127.0> Supervisor riak_core_handoff_sup had child riak_core_handoff_listener_sup started with riak_core_handoff_listener_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,riak_core_handoff_listener,{bad_return_value,{error,eaddrinuse}}}} in context start_error
2015-10-15 20:24:13.850 [error] <0.121.0> Supervisor riak_core_sup had child riak_core_handoff_sup started with riak_core_handoff_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,riak_core_handoff_listener_sup,{shutdown,{failed_to_start_child,riak_core_handoff_listener,{bad_return_value,{error,eaddrinuse}}}}}} in context start_error
2015-10-15 20:24:13.852 [error] <0.119.0> CRASH REPORT Process <0.119.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,riak_core_handoff_sup,{shutdown,{failed_to_start_child,riak_core_handoff_listener_sup,{shutdown,{failed_to_start_child,riak_core_handoff_listener,{bad_return_value,{error,eaddrinuse}}}}}}}},{riak_core_app,start,[normal,[]]}} in application_master:init/4 line 133
2015-10-16 08:33:01.580 [error] <0.131.0> CRASH REPORT Process riak_core_handoff_listener with 1 neighbours exited with reason: bad return value: {error,eaddrinuse} in gen_server:init_it/6 line 332
2015-10-16 08:33:01.580 [error] <0.130.0> Supervisor riak_core_handoff_listener_sup had child riak_core_handoff_listener started with riak_core_handoff_listener:start_link() at undefined exit with reason bad return value: {error,eaddrinuse} in context start_error
2015-10-16 08:33:01.581 [error] <0.127.0> Supervisor riak_core_handoff_sup had child riak_core_handoff_listener_sup started with riak_core_handoff_listener_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,riak_core_handoff_listener,{bad_return_value,{error,eaddrinuse}}}} in context start_error
2015-10-16 08:33:01.583 [error] <0.121.0> Supervisor riak_core_sup had child riak_core_handoff_sup started with riak_core_handoff_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,riak_core_handoff_listener_sup,{shutdown,{failed_to_start_child,riak_core_handoff_listener,{bad_return_value,{error,eaddrinuse}}}}}} in context start_error
2015-10-16 08:33:01.583 [error] <0.119.0> CRASH REPORT Process <0.119.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,riak_core_handoff_sup,{shutdown,{failed_to_start_child,riak_core_handoff_listener_sup,{shutdown,{failed_to_start_child,riak_core_handoff_listener,{bad_return_value,{error,eaddrinuse}}}}}}}},{riak_core_app,start,[normal,[]]}} in application_master:init/4 line 133
2015-10-16 08:34:12.737 [error] <0.131.0> CRASH REPORT Process riak_core_handoff_listener with 1 neighbours exited with reason: bad return value: {error,eaddrinuse} in gen_server:init_it/6 line 332
2015-10-16 08:34:12.738 [error] <0.130.0> Supervisor riak_core_handoff_listener_sup had child riak_core_handoff_listener started with riak_core_handoff_listener:start_link() at undefined exit with reason bad return value: {error,eaddrinuse} in context start_error
2015-10-16 08:34:12.739 [error] <0.127.0> Supervisor riak_core_handoff_sup had child riak_core_handoff_listener_sup started with riak_core_handoff_listener_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,riak_core_handoff_listener,{bad_return_value,{error,eaddrinuse}}}} in context start_error
2015-10-16 08:34:12.740 [error] <0.121.0> Supervisor riak_core_sup had child riak_core_handoff_sup started with riak_core_handoff_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,riak_core_handoff_listener_sup,{shutdown,{failed_to_start_child,riak_core_handoff_listener,{bad_return_value,{error,eaddrinuse}}}}}} in context start_error
2015-10-16 08:34:12.742 [error] <0.119.0> CRASH REPORT Process <0.119.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,riak_core_handoff_sup,{shutdown,{failed_to_start_child,riak_core_handoff_listener_sup,{shutdown,{failed_to_start_child,riak_core_handoff_listener,{bad_return_value,{error,eaddrinuse}}}}}}}},{riak_core_app,start,[normal,[]]}} in application_master:init/4 line 133
2015-10-16 08:41:09.946 [error] <0.131.0> CRASH REPORT Process riak_core_handoff_listener with 1 neighbours exited with reason: bad return value: {error,eaddrinuse} in gen_server:init_it/6 line 332
2015-10-16 08:41:09.947 [error] <0.130.0> Supervisor riak_core_handoff_listener_sup had child riak_core_handoff_listener started with riak_core_handoff_listener:start_link() at undefined exit with reason bad return value: {error,eaddrinuse} in context start_error
2015-10-16 08:41:09.948 [error] <0.127.0> Supervisor riak_core_handoff_sup had child riak_core_handoff_listener_sup started with riak_core_handoff_listener_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,riak_core_handoff_listener,{bad_return_value,{error,eaddrinuse}}}} in context start_error
2015-10-16 08:41:09.949 [error] <0.121.0> Supervisor riak_core_sup had child riak_core_handoff_sup started with riak_core_handoff_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,riak_core_handoff_listener_sup,{shutdown,{failed_to_start_child,riak_core_handoff_listener,{bad_return_value,{error,eaddrinuse}}}}}} in context start_error
2015-10-16 08:41:09.949 [error] <0.119.0> CRASH REPORT Process <0.119.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,riak_core_handoff_sup,{shutdown,{failed_to_start_child,riak_core_handoff_listener_sup,{shutdown,{failed_to_start_child,riak_core_handoff_listener,{bad_return_value,{error,eaddrinuse}}}}}}}},{riak_core_app,start,[normal,[]]}} in application_master:init/4 line 133
2015-10-16 08:41:38.923 [error] <0.143.0> CRASH REPORT Process <0.143.0> with 0 neighbours exited with reason: no match of right hand value {error,{error_db_destroy,"IO error: ./data/cluster_meta/trees/LOCK: Permission denied"}} in hashtree:destroy/1 line 275 in gen_server:init_it/6 line 328
2015-10-16 08:41:38.924 [error] <0.121.0> Supervisor riak_core_sup had child riak_core_metadata_hashtree started with riak_core_metadata_hashtree:start_link() at undefined exit with reason no match of right hand value {error,{error_db_destroy,"IO error: ./data/cluster_meta/trees/LOCK: Permission denied"}} in hashtree:destroy/1 line 275 in context start_error
2015-10-16 08:41:38.925 [error] <0.119.0> CRASH REPORT Process <0.119.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,riak_core_metadata_hashtree,{{badmatch,{error,{error_db_destroy,"IO error: ./data/cluster_meta/trees/LOCK: Permission denied"}}},[{hashtree,destroy,1,[{file,"src/hashtree.erl"},{line,275}]},{hashtree_tree,create_node,2,[{file,"src/hashtree_tree.erl"},{line,463}]},{hashtree_tree,new,2,[{file,"src/hashtree_tree.erl"},{line,193}]},{riak_core_metadata_hashtree,init,1,[{file,"src/riak_core_metadata_hashtree.erl"},{line,172}]},{gen_server,init_it,6,[{file,"gen_s..."},...]},...]}}},...} in application_master:init/4 line 133
